
### POST 1 user
POST https://floco-app.herokuapp.com/users
Content-Type: application/json

{
    "firstName": "test_profile",
    "lastName": "test_profile",
    "avatar": "https://images.assetsdelivery.com/compings_v2/gmast3r/gmast3r1710/gmast3r171002485.jpg",
    "email": "test_profile",
    "pseudo": "test_profile",
    "password": "test_profile",
  "isOAuth": false
}

### POST 1 pot
POST https://floco-app.herokuapp.com/pots
Content-Type: application/json

{
    "width": 12,
    "length": 11,
    "depth": 14,
    "UserUuid": "1"
}
###POST 1 seed
POST https://floco-app.herokuapp.com/seeds
Content-Type: application/json

{
    "name": "rose",
    "status": "vulnérable",
    "type": "vivace",
    "environment": "extérieur/intérieur",
    "season": "printemps",
    "exposure": "sun",
    "spray": "fréquente",
    "PotUuid": "1"
}

### POST 1 plant
POST https://floco-app.herokuapp.com/plants
Content-Type: application/json

{
    "image": "https://static.aujardin.info/cache/th/img9/philodendron-feuille-600x450.jpg",
    "SeedUuid": "1"
}

### POST 1 location
POST https://floco-app.herokuapp.com/locations
Content-Type: application/json

{
    "latitude": 20,
    "longitude": 20,
    "PlantUuid": "1"
}